version: "3.7"

services:
  n8n:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: n8n-puppeteer
    ports:
      - "5680:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepassword
      - N8N_COMMUNITY_PACKAGES=n8n-nodes-puppeteer

volumes:
  n8n_data:
